kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs.dynamic/ifs
            - name: NFS_SERVER
              value: ip-10-0-2-206.ec2.internal
            - name: NFS_PATH
              value: /home/data/persistent01
      volumes:
        - name: nfs-client-root
          nfs:
            server: ip-10-0-2-206.ec2.internal
            path: /home/data/persistent01

